### ISSUE TITLE
Hi - Curious if we can update this to something I need? 

### ISSUE THREAD

**Issue by LeonScene** [ejedev/TwitchCommand#1]
I was hoping we can chat? I'd like a private (exclusive) version of
chaterrino2 built for me.

The features are pretty simple - I am able to chat in multiple
streams, and maybe some auto messages, like welcome to the stream and
stuff.

I can provide more details if you are interested.
Obviously this is a custom project and I'd like to pay you for the updates.

Thanks!

**Comment by ejedev** [comment]
Hey Leon,

Unfortunately this project is not a Twitch bot but a remote administration tool that uses twitch chat as a server. You might have better luck talking to a developer of a similar twitch bot to what you're looking for.

Thanks
